export const CHANGE_PREFERRED_SIZE = 'CHANGE_PREFERRED_SIZE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_GRAND_TOTAL = 'UPDATE_GRAND_TOTAL';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const EMPTY_CART_ITEMS = 'EMPTY_CART_ITEMS';
export const HANDLE_ADDRESS_UPSERT = 'HANDLE_ADDRESS_UPSERT';
export const UPDATE_ADDRESS_INFO = 'UPDATE_ADDRESS_INFO';
